### ISSUE TITLE
argparse==1.3.1 in requirements.txt not found

### ISSUE THREAD

**Issue by snacsnoc** [mpaepper/content-chatbot#1]
Good afternoon, when installing the requirements via `pip install -r requirements.txt`, pip gave me an error:
```
ERROR: Could not find a version that satisfies the requirement argparse==1.3.1 (from versions: 0.1.0, 0.2.0, 0.3.0, 0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 0.9.0, 0.9.1, 1.0, 1.0.1, 1.1, 1.2.1, 1.2.2, 1.3.0, 1.4.0)
ERROR: No matching distribution found for argparse==1.3.1
```

When I view [argparse on PyPi](https://pypi.org/project/argparse/#history), 1.3.1 is not available. I was able to fix this issue by using argparse 1.4.0.

**Comment by silentsilas** [comment]
I had to do the same, and I also had to pip install `openai`, `tiktoken`, and `faiss-cpu`

**Comment by mpaepper** [comment]
Ah, good catch, sorry about that. 
I've updated the requirements.txt and tested it with a new conda env. Should all work now.
Thanks for creating an issue @snacsnoc !
