### ISSUE TITLE
4 most similar docs

### ISSUE THREAD

**Issue by m1o9h9o9r** [mpaepper/content-chatbot#9]
If I understand correctly, the default is set to search for 4 most relevant docs. Is it possible to change this somehow?

**Comment by mpaepper** [comment]
Yep, it is:

default is k=4, but you can change it:

```python
chain = VectorDBQAWithSourcesChain.from_llm(
          llm=OpenAI(temperature=0, verbose=True), vectorstore=store, k=10)
```
